spark.master spark://spark-master:7077
spark.eventLog.enabled true
spark.eventLog.dir file:/spark-events
spark.sql.warehouse.dir hdfs://namenode:9000/user/hive/warehouse
spark.hadoop.fs.defaultFS hdfs://namenode:9000
