CREATE DATABASE IF NOT EXISTS zhiyuan
  DEFAULT CHARACTER SET utf8mb4
  DEFAULT COLLATE utf8mb4_unicode_ci;

CREATE DATABASE IF NOT EXISTS hive_metastore
  DEFAULT CHARACTER SET latin1
  DEFAULT COLLATE latin1_swedish_ci;

CREATE USER IF NOT EXISTS 'hive'@'%' IDENTIFIED BY 'hive123456';
GRANT ALL PRIVILEGES ON hive_metastore.* TO 'hive'@'%';

CREATE USER IF NOT EXISTS 'zhiyuan_app'@'%' IDENTIFIED BY 'zhiyuan123456';
GRANT ALL PRIVILEGES ON zhiyuan.* TO 'zhiyuan_app'@'%';

FLUSH PRIVILEGES;
